//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUAYENETAKIP.DBOBECT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MUAYNETAKIPDBEntities : DbContext
    {
        public MUAYNETAKIPDBEntities()
            : base("name=MUAYNETAKIPDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ANABILIMDALI> ANABILIMDALI { get; set; }
        public virtual DbSet<DOKTOR> DOKTOR { get; set; }
        public virtual DbSet<HASTA> HASTA { get; set; }
        public virtual DbSet<MUAYENE> MUAYENE { get; set; }
        public virtual DbSet<RANDEVU> RANDEVU { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
